kind: Deployment
apiVersion: apps/v1  
metadata:
  name:  regapp
  namespace: #dev    
  labels:
    app: reg
spec: 
  replicas: 1     
  selector:
    matchLabels:
      app: reg
  template:
    metadata:
      name: regapp
      labels: 
        app: reg
    spec: 
      containers:
      - name: regapp
        image: pdannyable/springboot:latest
        ports:
        - containerPort: 8080  

